# Generated by Django 4.1.3 on 2022-12-08 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BeritaModel',
        ),
    ]
