# Generated by Django 4.1.3 on 2022-12-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_beritaapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beritaapi',
            old_name='athor',
            new_name='author',
        ),
    ]
