# Generated by Django 4.1.3 on 2022-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_athor_beritaapi_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeritaApiBaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('contentSnippet', models.TextField()),
                ('isoDate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
