# Generated by Django 4.1.3 on 2022-12-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_beritaapibaru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beritaapi',
            name='author',
        ),
    ]
