# Generated by Django 4.1.3 on 2022-12-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_beritaapi_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beritaapi',
            old_name='cotent',
            new_name='content',
        ),
    ]
