# Generated by Django 4.1.3 on 2022-12-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_beritaapi_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeritaApi',
        ),
    ]
