# Generated by Django 4.1.3 on 2022-12-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_beritaapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaapibaru',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
