# Generated by Django 4.1.3 on 2022-12-14 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_beritaapibaru_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaapibaru',
            name='isoDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
