# Generated by Django 4.1.3 on 2022-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_beritaapibaru_isodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaapibaru',
            name='isoDate',
            field=models.CharField(max_length=1000),
        ),
    ]
